/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.oop_project;
import java.io.File;
import java.io.FileWriter;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author VWPiseth
 */
public class AssignProject extends javax.swing.JFrame {

    /**
     * Creates new form AssignProject
     */
    public AssignProject() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jColorChooser2 = new javax.swing.JColorChooser();
        jColorChooser3 = new javax.swing.JColorChooser();
        ProjectAssigning = new javax.swing.JLabel();
        ProjectTitleLabel = new javax.swing.JLabel();
        txtProjectTitle = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtProjectDescription = new javax.swing.JTextArea();
        DeadlineLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtProjectDeadline = new javax.swing.JTextField();
        AssignProjectButton = new javax.swing.JButton();
        BackMenuButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        ProjectDepartmentLabel = new javax.swing.JLabel();
        txtEmployeeID = new javax.swing.JTextField();
        txtProjectDepartment = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        ProjectAssigning.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ProjectAssigning.setText("Project/Task Assigning");

        ProjectTitleLabel.setText("Project/Task Title");

        jLabel2.setText("Project/Task Desrciption");

        txtProjectDescription.setColumns(20);
        txtProjectDescription.setRows(5);
        jScrollPane1.setViewportView(txtProjectDescription);

        DeadlineLabel.setText("Deadline (DD/MM/YY)");

        txtProjectDeadline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProjectDeadlineActionPerformed(evt);
            }
        });

        AssignProjectButton.setText("Assign");
        AssignProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignProjectButtonActionPerformed(evt);
            }
        });

        BackMenuButton.setText("Back to Menu");
        BackMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackMenuButtonActionPerformed(evt);
            }
        });

        jLabel3.setText("Employee ID");

        ProjectDepartmentLabel.setText("Department");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(ProjectAssigning))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BackMenuButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(AssignProjectButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(ProjectTitleLabel)
                                    .addComponent(DeadlineLabel)
                                    .addComponent(jLabel3)
                                    .addComponent(ProjectDepartmentLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtProjectTitle)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                                        .addComponent(txtProjectDeadline)
                                        .addComponent(txtProjectDepartment))
                                    .addComponent(jLabel1)
                                    .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(6, 6, 6)))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(ProjectAssigning)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ProjectTitleLabel)
                    .addComponent(txtProjectTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ProjectDepartmentLabel)
                    .addComponent(txtProjectDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BackMenuButton)
                            .addComponent(AssignProjectButton))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DeadlineLabel)
                            .addComponent(txtProjectDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtProjectDeadlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProjectDeadlineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProjectDeadlineActionPerformed

    private void AssignProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignProjectButtonActionPerformed
          // TODO add your handling code here:
          // code to load data into table
          //validation for not leave blank data
          if(txtProjectTitle.getText().equals("")||txtProjectDescription.getText().equals("")||txtProjectDeadline.getText().equals("")||txtProjectDepartment.getText().equals("")||txtEmployeeID.getText().equals("")){
              JOptionPane.showMessageDialog(this, "Please Enter All Data !");
          } else {
              String data[] = {txtProjectTitle.getText(),txtProjectDescription.getText(),txtProjectDepartment.getText(),txtEmployeeID.getText(),txtProjectDeadline.getText()};
              File file = new File("projectlist.txt");
            if (file.exists()){
                try(FileWriter writer = new FileWriter(file, true)){
                    //writer.write("Project Title: " + txtProjectTitle.getText()+"\n" + "Project Description: " + txtProjectDescription.getText()+ "\n" + "Project Department: " +txtProjectDepartment.getText() +  "\n" + "Employee ID: " + txtEmployeeID.getText() + "\n" + "Project Deadline : " +txtProjectDeadline.getText() + "\n");
                    writer.write(txtProjectTitle.getText()+" ; "+txtProjectDescription.getText()+" ; "+txtProjectDescription.getText()+ " ; "+ txtProjectDepartment.getText()+" ; "+ txtEmployeeID.getText() + " ; "+txtProjectDeadline.getText() + " ; ");
                    writer.write(System.getProperty("line.separator"));
                    writer.close();
                    JOptionPane.showMessageDialog(null, "Assigned Successfully!");
                    setVisible(false);
                    new AssignProject().setVisible(true);
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Error");
                }
            }
            else{
                try(FileWriter writer = new FileWriter(file)){
                    writer.write(txtProjectTitle.getText()+" ; "+txtProjectDescription.getText()+" ; "+txtProjectDescription.getText()+ " ; "+ txtProjectDepartment.getText()+" ; "+ txtEmployeeID.getText() + " ; "+txtProjectDeadline.getText());
                    writer.write(System.getProperty("line.separator"));
                    writer.close();
                    JOptionPane.showMessageDialog(null, "Assigned Successfully!");
                    setVisible(false);
                    new AssignProject().setVisible(true);
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(null, "Error");
                }
            } 
//              ViewProject viewproject = new ViewProject();
//              viewproject.setVisible(true);
//             DefaultTableModel tblModel = (DefaultTableModel)viewproject.jTable2.getModel();
//             tblModel.addRow(data);
          }
    }//GEN-LAST:event_AssignProjectButtonActionPerformed

    private void BackMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackMenuButtonActionPerformed
        // TODO add your handling code here:
        AdminMenu adminMenu = new AdminMenu();
        adminMenu.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_BackMenuButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AssignProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AssignProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AssignProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AssignProject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AssignProject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton AssignProjectButton;
    private javax.swing.JButton BackMenuButton;
    private javax.swing.JLabel DeadlineLabel;
    private javax.swing.JLabel ProjectAssigning;
    private javax.swing.JLabel ProjectDepartmentLabel;
    private javax.swing.JLabel ProjectTitleLabel;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JColorChooser jColorChooser2;
    private javax.swing.JColorChooser jColorChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtEmployeeID;
    private javax.swing.JTextField txtProjectDeadline;
    private javax.swing.JTextField txtProjectDepartment;
    private javax.swing.JTextArea txtProjectDescription;
    private javax.swing.JTextField txtProjectTitle;
    // End of variables declaration//GEN-END:variables
}
